package demo.mapper;

import demo.model.MiaoshaUser;
import demo.model.MiaoshaUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MiaoshaUserMapper<T> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Fri May 15 11:28:40 CST 2020
     */
    int countByExample(MiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Fri May 15 11:28:40 CST 2020
     */
    int deleteByExample(MiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Fri May 15 11:28:40 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Fri May 15 11:28:40 CST 2020
     */
    int insert(MiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Fri May 15 11:28:40 CST 2020
     */
    int insertSelective(MiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Fri May 15 11:28:40 CST 2020
     */
    List<MiaoshaUser> selectByExample(MiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Fri May 15 11:28:40 CST 2020
     */
    MiaoshaUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Fri May 15 11:28:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") MiaoshaUser record, @Param("example") MiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Fri May 15 11:28:40 CST 2020
     */
    int updateByExample(@Param("record") MiaoshaUser record, @Param("example") MiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Fri May 15 11:28:40 CST 2020
     */
    int updateByPrimaryKeySelective(MiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_user
     *
     * @mbggenerated Fri May 15 11:28:40 CST 2020
     */
    int updateByPrimaryKey(MiaoshaUser record);

    public MiaoshaUser getById(@Param("id")long id);


}